window.LCAI_HOLDINGS = {
  "updatedAt": "2026-06-18",
  "holdings": [
    {
      "id": "pingan",
      "name": "平安好医生",
      "account": "gt",
      "symbol": "116.01833",
      "shares": 43600,
      "costPerShare": 14.434,
      "currency": "HKD",
      "hk": true,
      "fallbackPrice": 8.05,
      "sold": false
    },
    {
      "id": "tencent",
      "name": "腾讯控股",
      "account": "gt",
      "symbol": "116.00700",
      "shares": 200,
      "costPerShare": 467.644,
      "currency": "HKD",
      "hk": true,
      "fallbackPrice": 445.4,
      "sold": false
    },
    {
      "id": "weimob",
      "name": "微盟集团",
      "account": "gt",
      "symbol": "116.02013",
      "shares": 38000,
      "costPerShare": 1.376,
      "currency": "HKD",
      "hk": true,
      "fallbackPrice": 1.32,
      "sold": false
    },
    {
      "id": "jd_health",
      "name": "京东健康",
      "account": "gt",
      "symbol": "116.06618",
      "shares": 800,
      "costPerShare": 37.341,
      "currency": "HKD",
      "hk": true,
      "fallbackPrice": 35.42,
      "sold": false
    },
    {
      "id": "seres_hb",
      "name": "赛力斯",
      "account": "hb",
      "symbol": "1.601127",
      "shares": 3000,
      "costPerShare": 164.671,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 64.81,
      "sold": false
    },
    {
      "id": "envicool_hb",
      "name": "英维克",
      "account": "hb",
      "symbol": "0.002837",
      "shares": 1000,
      "costPerShare": 74.253,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 74.37,
      "sold": false
    },
    {
      "id": "jcet_hb",
      "name": "长电科技",
      "account": "hb",
      "symbol": "1.600584",
      "shares": 500,
      "costPerShare": 81.318,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 83.03,
      "sold": true
    },
    {
      "id": "huaqiang_hb",
      "name": "深圳华强",
      "account": "hb",
      "symbol": "0.000062",
      "shares": 1700,
      "costPerShare": 31.695,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 32.06,
      "sold": true
    },
    {
      "id": "guoxuan_hb",
      "name": "国轩高科",
      "account": "hb",
      "symbol": "0.002074",
      "shares": 700,
      "costPerShare": 30.015,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 29.71,
      "sold": true
    },
    {
      "id": "aopu_hb",
      "name": "奥普光电",
      "account": "hb",
      "symbol": "0.002338",
      "shares": 400,
      "costPerShare": 54.586,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 54.0,
      "sold": true
    },
    {
      "id": "deye_hb",
      "name": "德业股份",
      "account": "hb",
      "symbol": "1.605117",
      "shares": 200,
      "costPerShare": 103.182,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 103.2,
      "sold": true
    },
    {
      "id": "megmeet",
      "name": "麦格米特",
      "account": "hb",
      "symbol": "0.002851",
      "shares": 1100,
      "costPerShare": 153.27,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 135.24,
      "sold": true
    },
    {
      "id": "ubtech",
      "name": "优必选",
      "account": "gt",
      "symbol": "116.09880",
      "shares": 1150,
      "costPerShare": 110.99,
      "currency": "HKD",
      "hk": true,
      "fallbackPrice": 106.5,
      "sold": true
    },
    {
      "id": "jiangtong",
      "name": "江西铜业",
      "account": "hb",
      "symbol": "1.600362",
      "shares": 200,
      "costPerShare": 79.48,
      "currency": "CNY",
      "hk": false,
      "fallbackPrice": 43.05,
      "sold": true
    }
  ]
};
